language: python
sudo: false
cache:
  directories:
  - "$HOME/.pip-cache/"
env:
  global:
  - PIP_WHEEL_DIR=$HOME/.cache/pip/wheels
  - PIP_FIND_LINKS=file://$HOME/.cache/pip/wheels
python:
- '3.6'
install:
- pip wheel -r requirements.txt
- pip install .
script: pytest
deploy:
  provider: pypi
  user: mrahnis
  password:
    secure: cmo3D99wSSDn6LrSlxRLRr7RioyGw7UDIHSWMikJRIcKI0jAmoUOwPczUYRsNmdTMC32cjNYfE9FlN+0rg629J8ZvpeBidrdj95BTN5rTZTRd3KN2i8m4jJg0z+pe7OBza6XoaGDF1vpAdPfxi+OHy4jG4Wm73CGGpR/CwT0uS0E4chBwRnpqP4HOXdWWmFqDXAvGS/Lh2dqJWgH5MPs3Qas6hm6GWUnEEuuXuJdYK+X3wCO4edUuYR5Uf5rNxKYUezogbVmfqY1vk5yIG0xWIF5BYUBTB5alWtb52SD3X4tqx04JITt2vTqor9i0rGksBwvwr2xWcBnz7c/OkkvLOFOWAFdT2ywDOHreXr5Bbh0N4z4Mm3++T+YwcbfBqiKi+vMN90p2l8Bugw+eV0AF2NlQkRfGTsRe92pgaWuFrJsmX4PNrwHygkmhhZnBIj1Ti7/hSwG9p6UrnbNWwpwyTbUi/c2HWOKBg4+IoasiHdANQI3z5QFZycS7fkxTdm9Bes04RTkzswYhyFZzc0vlPUwyo9gA0NmRwLRTCDmjE35cwYt2CuNELPrISrqA/Kd6jRLNcPg/zzx4e4rryJgJ19UeOfzQhvrvIAokNuySHdwm9wF6TTmj3BnLQN1Tk1dHIWIeohhilW0gFKlfKf+/lW0owavO0HTA4jxIyZoFNw=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: mrahnis/jxl2txt
  skip_cleanup: true
