language: python
sudo: false
cache:
  directories:
  - "$HOME/.pip-cache/"
env:
  global:
  - PIP_WHEEL_DIR=$HOME/.cache/pip/wheels
  - PIP_FIND_LINKS=file://$HOME/.cache/pip/wheels
python:
- '3.6'
install:
- pip wheel -r requirements.txt
- pip install .
script: pytest
deploy:
  provider: pypi
  user: mrahnis
  password:
    secure: q5PBqEj+J88zOFc9f4mdrcXbM76l9l8A6KYDXwHnpjrwf2Ne6zdkGWQd8gUQ/LT9uFU6lQGqrDDsPBkbQ4c6mePIaG+6ErnHj3XSP+ZCP5kqiyKod75EoREgdGdC2BNw5uk6n7H9FjfFw7oELn0X6VjvdY6GPZFlFTgx03FLtrRo8Cluu63U9M3b74AusEIuj7lQ3rzcEFydHgGVFG26Urjuzb/DlhYHzILGozejnTUQ8dU+xeeFHDvKlYis+kImHT0kbxtwBFtwbHKo+Mq+Qta7PW2pghfsIvPZ5xCUzWR8tTRU/XMGGdVs6XXtzieVNReYkL5oEr97oOlGiub4imyQtgCR8StV1mGwj3JoY8BhklMgXJXGXNbv4HZojOv2C3PCIU+EeuBs3UnPNSIRiIiYViXzO/FdRtbJn/K5t43/aIgyXA3jserAPWVc4JFvddGT2M4dfv2iCpusC6JSVgw1Kt1w3Xoodwt2DASeUKspEVJcYufKzYS3cv+xdxC0qJ85Trb/zDAwMObKmPdxutoaDpEGytHnHxzxea7fc73DAMB8GjyfvddyQTpVA9/PASsA3EJ9GAfZl6a2z47CtAXBsy/bXmHKw7btgMOCr7JeXCw3g/WLX45wbO72xM4ogPk2DOXYKilQrCixzgBM0iTTEgCd2ajv8E2+FpV42K8=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: mrahnis/jxl2txt
  skip_cleanup: true
