language: python
sudo: false
cache:
  directories:
  - "$HOME/.pip-cache/"
env:
  global:
  - PIP_WHEEL_DIR=$HOME/.cache/pip/wheels
  - PIP_FIND_LINKS=file://$HOME/.cache/pip/wheels
python:
- '3.7'
install:
- pip wheel -r requirements.txt
- pip install .
script: pytest
deploy:
  provider: pypi
  user: "__token__"
  password:
    secure: Z/BjRk30+8BiH0CrDq1HHZZZZWKML18wZZrA4EOhDiKfKsmTCUvU3qIJeKxGjQeLJfsAp+lniIvuHvOEJBwYNsUpbcRuOetElaoKa4p3Yy0Lq7cha77CCh7/ZuAExsKiFTq9Tv/w7NNMJ1msTH3qxmOn21+IH54NeqQsUe/yE8z/hQYrGIgm4S96AsCQUzEyu0fLh0X4wNynftqig/jannLQD9X1EV3NqRd6+O8ZVPOzPmGj5N9A9H+x+dO969zQMH8LJ8WjONK1fxCPHLPe5vGJM9dTlGG6D3Bb4PTMCF7/a6qU4Fp9MDba5TfPTaqcRd4JMaumNl8lZtHmAgi1aSUtjZhpLHrgXD/CLYoDQdgAj1dnUc55bEzpH4qUUxa7zUu+uDb3jaXoUwjJ8dMkEkih6LF2wwcvF2fsKE03btux95HMpKcS69djiOC0ZdiAtpHcsqQfcLlgPOQ704asp3rZXWZEPjYv3hHm5aVsozfiKk25QRBCpX6GrCrLUVY6oJjMliz5tfMSeessdR7Q1idhaQ6p9amUkbgV6ZNi6nwHVK+7LvJpqgcKafRMdiAuZJ6T47FwPHvSakeB4LWy3vakC74M88xKWH1NGrzjVVRsWb2yO/emhzIBNDZ5LNuh01BeH28+QIR7Z/dn0U9hMIgykwW7LBWBT/2QlRQfLtk=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: mrahnis/jxl2txt
  skip_cleanup: true
