[project]
name = "jxl2txt"
version = "0.1.0"
description = "Add a short description here"
authors = ["mrahnis <mrahnis@users.noreply.github.com>"]
channels = ["conda-forge"]
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]

[tasks]

[dependencies]
lxml = ">=5.1.0,<5.2"
setuptools = ">=69.0.3,<69.1"
pip = ">=23.3.2,<23.4"
click = ">=8.1.7,<8.2"
