package:
  name: jxl2txt
  version: "0.1.1"

source:
  git_url: https://github.com/mrahnis/jxl2txt.git
  git_rev: HEAD

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt
  entry_points:
    - jxl2txt = jxl2txt.jxl2txt:cli

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - click
    - lxml

test:
  imports:
    - jxl2txt
  commands:
    - jxl2txt --help

about:
  home: https://github.com/mrahnis/jxl2txt
  license: BSD
  license_file: LICENSE.txt