{% set pyproject = load_file_data('pyproject.toml') %}
{% set version = pyproject.get('project').get('version') %}

package:
  name: jxl2txt
  version: {{ version }}

source:
  git_url: https://github.com/mrahnis/jxl2txt.git
  git_rev: HEAD

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - jxl2txt = jxl2txt.jxl2txt:cli

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - click
    - lxml

test:
  imports:
    - jxl2txt
  commands:
    - jxl2txt --help

about:
  home: https://github.com/mrahnis/jxl2txt
  license: BSD
  license_file: LICENSE.txt

# https://github.com/conda/conda-build/issues/4807
# whatever_you_do_don't_load_setup_py_dataxxx!!!
